# branches to build
branches:
  except:
    - gh-pages
    - /^v\d/

sudo: required

language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=py37

matrix:
  exclude:
    - os: osx
      compiler: gcc

git:
  submodules: false

before_install:
  - uname -a
  - git submodule update --init --recursive

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

notifications:
  email:
    on_success: never
    on_failure: always
