# branches to build
branches:
  except:
    - gh-pages

language: c

os:
  - linux
  - osx

compiler:
    - clang
    - gcc

env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34

matrix:
  exclude:
    - os: osx
      compiler: gcc

git:
  submodules: false

before_install:
  - uname -a
  - git submodule update --init --recursive

install:
  - ./ci/travis_install.sh

script:
  - ./ci/travis_run.sh

notifications:
  email:
    on_success: never
    on_failure: never
