# branches to build
branches:
  except:
    - gh-pages

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\ci\\appveyor_run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "32"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      DISTRIBUTIONS: "sdist bdist_wheel"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.3"
      PYTHON_ARCH: "32"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.3"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      DISTRIBUTIONS: "bdist_wheel"

init:
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - cmd: git submodule update --init --recursive
  - cmd: powershell ci\\appveyor_install.ps1

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python setup.py test"

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py %DISTRIBUTIONS%"

artifacts:
  - path: dist\*

deploy:
  provider: GitHub
  auth_token:
    secure: im3lhTE73ST7rwUUhuz0KybfQ6Hr4GEWYDQ1aWmfD3WwRV1uoWdg8xRLNfCrK8X6
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
